CREATE TABLE {prefix}sermons_nl_kerkdienstgemist (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  event_id int(10) UNSIGNED NULL,
  remote_id bigint(10) UNSIGNED NULL,
  dt datetime NULL,
  dt_end datetime NULL,
  pastor varchar(255) NULL,
  title varchar(255) NULL,
  description text(65535) NOT NULL,
  audio_id int(10) UNSIGNED NULL,
  audio_url text NULL,
  audio_mimetype varchar(255) NULL,
  audio_live tinyint(1) DEFAULT 0 NOT NULL,
  audio_planned tinyint(1) DEFAULT 0 NOT NULL,
  video_id int(10) UNSIGNED NULL,
  video_url text NULL,
  video_mimetype varchar(255) NULL,
  video_live tinyint(1) DEFAULT 0 NOT NULL,
  video_planned tinyint(1) DEFAULT 0 NOT NULL,
  PRIMARY KEY  (id),
  UNIQUE KEY remote_id (remote_id),
  UNIQUE KEY audio_id (audio_id),
  UNIQUE KEY video_id (video_id)
  ) {charset_collate};
